/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as MeusAnunciosRouteImport } from './routes/meus-anuncios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAnunciosRoute = MeusAnunciosRouteImport.update({
  id: '/meus-anuncios',
  path: '/meus-anuncios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/meus-anuncios': typeof MeusAnunciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/meus-anuncios': typeof MeusAnunciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/buscar': typeof BuscarRoute
  '/meus-anuncios': typeof MeusAnunciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anunciar' | '/buscar' | '/meus-anuncios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anunciar' | '/buscar' | '/meus-anuncios'
  id: '__root__' | '/' | '/anunciar' | '/buscar' | '/meus-anuncios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  BuscarRoute: typeof BuscarRoute
  MeusAnunciosRoute: typeof MeusAnunciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-anuncios': {
      id: '/meus-anuncios'
      path: '/meus-anuncios'
      fullPath: '/meus-anuncios'
      preLoaderRoute: typeof MeusAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  BuscarRoute: BuscarRoute,
  MeusAnunciosRoute: MeusAnunciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
